secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD
resources:
- mysql-deployment.yaml
- drupal-deployment.yaml
- mysqldrupal-deployment.yaml
- php-deployment.yaml
- php-service.yaml