apiVersion: v1
kind: Service
metadata:
  name: mysql1
spec:
  type: NodePort
  ports:
  - port: 3306
  externalIPs:
    - 10.0.0.5
  selector:
    app: mysql1
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql1
spec:
  selector:
    matchLabels:
      app: mysql1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
      - image: mysql:5.6
        name: mysql1
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql1

