apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-13T14:25:22Z"
  generation: 1
  labels:
    app: myphp
  name: myphp
  namespace: default
  resourceVersion: "29459"
  selfLink: /apis/apps/v1/namespaces/default/deployments/myphp
  uid: 393e88a7-6788-49ca-a52e-ed3ea8e86825
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myphp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myphp
    spec:
      containers:
      - image: localhost:32000/myphp
        imagePullPolicy: Always
        name: myphp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-13T14:25:25Z"
    lastUpdateTime: "2021-08-13T14:25:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-13T14:25:22Z"
    lastUpdateTime: "2021-08-13T14:25:25Z"
    message: ReplicaSet "myphp-59f5b6b9b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
